name: stcrpy installation and tests conda workflow

on: [push]

jobs:
  conda-pypi-install:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.11"]
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -el {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
      - name: Install dependencies
        run: |
          pip install openbabel-wheel==3.1.1.21
          pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple stcrpy==0.1.25
          ANARCI --build_models
          conda install -c conda-forge -c schrodinger pymol-bundle numpy -y
      - name: Test import
        run: |
          python -c 'import stcrpy; stcrpy.fetch_TCR("7pb2")'