name: stcrpy installation and tests conda workflow

on: [push]

jobs:
  conda-pypi-install:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-13", "macos-latest"]
        python-version: ["3.11"]
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,schrodinger
          channel-priority: flexible
          show-channel-urls: true
      - name: Conda info
        shell: bash -el {0}
        run: |
          conda info
          conda config --show-sources
      - name: Conda list
        shell: pwsh
        run: conda list
      - name: Install dependencies
        shell: bash -el {0}
        run: |
          conda create -n env python==${{ matrix.python-version }}
          conda activate env
          pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple stcrpy==0.1.26
          pip list
      - name: Install pymol
        shell: bash -el {0}
        run: |
          conda activate env
          conda install -c conda-forge -c schrodinger pymol-bundle numpy -y
      - name: Build ANARCI Models
        shell: bash -el {0}
        run: |
          conda activate env
          ANARCI --build_models
      - name: Test import
        shell: bash -el {0}
        run: |
          conda activate env
          python -c 'import stcrpy; stcrpy.fetch_TCR("7pb2")'