name: stcrpy pypi installation

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        python -c 'import sys; sys.executable'
        pip install openbabel-wheel==3.1.1.21
        pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple stcrpy==0.1.25
        ANARCI --build_models
        conda install -c conda-forge -c schrodinger pymol-bundle numpy -y
    - name: Test import
      run: |
        python -c 'import stcrpy; stcrpy.fetch_TCR("7pb2")'

  build-macos:
    runs-on: macos-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -c 'import sys; sys.executable'
        pip install openbabel-wheel==3.1.1.21
        python -c 'import openbabel'
        pip install plip
        pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple stcrpy==0.1.25
        ANARCI --build_models
        conda install -c conda-forge -c schrodinger pymol-bundle numpy -y
    - name: Test import
      run: |
        python -c 'import stcrpy; stcrpy.fetch_TCR("7pb2")'

  build-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -c 'import sys; sys.executable'
        pip install openbabel-wheel==3.1.1.21
        python -c 'import openbabel'
        pip install plip
        pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple stcrpy==0.1.25
        ANARCI --build_models
        conda install -c conda-forge -c schrodinger pymol-bundle numpy -y
      shell: bash  # Use bash for conda compatibility
    - name: Test import
      run: |
        python -c 'import stcrpy; stcrpy.fetch_TCR("7pb2")'
      shell: bash
