name: stcrpy installation and tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        pip install openbabel-wheel
        pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple anarci-mhc==0.0.6
        ANARCI --build_models
        pip install biopython numpy lxml openbabel-wheel rdkit pandas matplotlib scipy scikit-learn plip
        pip install .
        conda install -c conda-forge -c schrodinger pymol-bundle numpy -y

    - name: Test with unittest
      run: |
        cd test
        python -m unittest
        
